(function(){
'use strict';
var KEY='whispervault_v3_state', AGE='whispervault_age_ok';
var empty={scripts:[],sources:[],prefs:{favoriteVoiceURI:'',rate:1,pitch:1,volume:1}};
var state=load(),editId=null,current=null,chunks=[],chunk=0,paused=false,after='';
function $(id){return document.getElementById(id)}
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'{}');return {scripts:x.scripts||[],sources:x.sources||[],prefs:Object.assign({},empty.prefs,x.prefs||{})}}catch(e){return clone(empty)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2)}
function openD(x){var d=$(x);if(d&&!d.open)d.showModal()}
function closeD(x){var d=$(x);if(d&&d.open)d.close()}
function wc(s){return String(s||'').trim().split(/\s+/).filter(Boolean).length}
function tagsFrom(t){var a=[],m,re=/\[([^\]]+)\]/g;while((m=re.exec(t||'')))a.push(m[1].trim());var c=a.find(function(x){return /^(F4M|M4F|F4F|M4M|F4A|M4A|A4A)$/i.test(x)});return {category:c?c.toUpperCase():'',tags:a.filter(function(x){return x!==c}).slice(0,12)}}
function stat(k,v){return '<div class="stat"><strong>'+v+'</strong><span>'+esc(k)+'</span></div>'}
function render(){
 var q=($('searchInput').value||'').toLowerCase(),cat=$('categoryFilter').value||'all',sort=$('sortSelect').value||'newest';
 var cats=[...new Set(state.scripts.map(function(x){return x.category}).filter(Boolean))].sort(),old=$('categoryFilter').value;
 $('categoryFilter').innerHTML='<option value="all">All categories</option>'+cats.map(function(c){return '<option>'+esc(c)+'</option>'}).join('');$('categoryFilter').value=cats.indexOf(old)>=0?old:'all';
 var a=state.scripts.filter(function(s){return (cat==='all'||s.category===cat)&&(!q||[s.title,s.author,(s.tags||[]).join(' '),s.text].join(' ').toLowerCase().indexOf(q)>=0)});
 if(sort==='title')a.sort(function(x,y){return x.title.localeCompare(y.title)});else if(sort==='favorites')a.sort(function(x,y){return (y.favorite?1:0)-(x.favorite?1:0)||(y.updatedAt-x.updatedAt)});else a.sort(function(x,y){return y.updatedAt-x.updatedAt});
 $('libraryGrid').innerHTML=a.map(scriptCard).join('');$('emptyState').hidden=state.scripts.length>0;
 $('sourceGrid').innerHTML=state.sources.slice().sort(function(x,y){return y.createdAt-x.createdAt}).map(sourceCard).join('');$('sourceEmpty').hidden=state.sources.length>0;
 $('statsRow').innerHTML=stat('Scripts',state.scripts.length)+stat('Sources',state.sources.length)+stat('Favorites',state.scripts.filter(function(x){return x.favorite}).length)+stat('Words',state.scripts.reduce(function(n,s){return n+wc(s.text)},0).toLocaleString());
}
function scriptCard(s){var tg=(s.tags||[]).slice(0,6).map(function(t){return '<span class="tag">'+esc(t)+'</span>'}).join('');return '<article class="card"><div class="eyebrow">'+esc(s.category||'OTHER')+'</div><h4>'+esc(s.title)+'</h4><div class="meta"><span>'+esc(s.author||'Unknown author')+'</span><span>•</span><span>'+wc(s.text).toLocaleString()+' words</span></div><div class="tag-row">'+tg+'</div><div class="card-preview">'+esc(s.text)+'</div><div class="card-actions"><button class="primary" data-play="'+s.id+'">▶ Listen</button><button class="ghost '+(s.favorite?'fav':'')+'" data-fav="'+s.id+'">'+(s.favorite?'★':'☆')+'</button><button class="ghost" data-edit="'+s.id+'">Edit</button>'+(s.source?'<a class="ghost linklike" target="_blank" rel="noopener" href="'+esc(s.source)+'">Source ↗</a>':'')+'<button class="danger" data-delete="'+s.id+'">Delete</button></div></article>'}
function sourceCard(s){var tg=(s.tags||[]).slice(0,6).map(function(t){return '<span class="tag">'+esc(t)+'</span>'}).join('');return '<article class="source-card"><div class="eyebrow">'+esc(s.category||'SOURCE')+'</div><h4>'+esc(s.title||s.url)+'</h4><div class="meta"><span>'+esc(s.author||'')+'</span></div><div class="tag-row">'+tg+'</div><div class="card-actions"><a class="ghost linklike" target="_blank" rel="noopener" href="'+esc(s.url)+'">Open source ↗</a><button class="primary" data-use-source="'+s.id+'">Add script</button><button class="danger" data-source-delete="'+s.id+'">Remove</button></div></article>'}
function resetForm(src){editId=null;$('scriptDialogTitle').textContent='Add script';$('scriptTitle').value=src?src.title||'':'';$('scriptAuthor').value=src?src.author||'':'';$('scriptCategory').value=src&&src.category?src.category:'Other';$('scriptTags').value=src?(src.tags||[]).join(', '):'';$('scriptSource').value=src?src.url||'':'';$('scriptPermission').value='unknown';$('scriptText').value=''}
function edit(i){var s=state.scripts.find(function(x){return x.id===i});if(!s)return;editId=i;$('scriptDialogTitle').textContent='Edit script';$('scriptTitle').value=s.title;$('scriptAuthor').value=s.author||'';$('scriptCategory').value=s.category||'Other';$('scriptTags').value=(s.tags||[]).join(', ');$('scriptSource').value=s.source||'';$('scriptPermission').value=s.permission||'unknown';$('scriptText').value=s.text||'';openD('scriptDialog')}
function addLinks(){var n=0;$('sourceUrls').value.split(/\r?\n/).map(function(x){return x.trim()}).filter(Boolean).forEach(function(url){if(!/^https?:\/\//i.test(url)||state.sources.some(function(s){return s.url===url}))return;state.sources.push({id:id(),url:url,title:$('sourceNote').value||url,author:'',category:'',tags:[],createdAt:Date.now()});n++});$('sourceImportSummary').textContent='Added '+n+' new source link'+(n===1?'':'s')+'.';$('sourceUrls').value='';save()}
async function reddit(next){var token=$('redditToken').value.trim()||sessionStorage.getItem('wv_reddit_token')||'';if(!token){$('redditSyncStatus').textContent='Paste a Reddit OAuth access token first.';return}sessionStorage.setItem('wv_reddit_token',token);var sub=$('redditSubreddit').value.trim().replace(/^r\//,'')||'gonewildaudio',q=$('redditQuery').value.trim()||'[Script Offer]',p=new URLSearchParams({q:q,restrict_sr:'1',limit:'100',sort:$('redditSort').value,t:'all',raw_json:'1'});if(next&&after)p.set('after',after);$('redditSyncStatus').textContent='Contacting Reddit…';
 try{var r=await fetch('https://oauth.reddit.com/r/'+encodeURIComponent(sub)+'/search?'+p.toString(),{headers:{Authorization:'Bearer '+token,'User-Agent':'WhisperVaultPersonal/3.0'}});if(!r.ok)throw new Error('Reddit returned '+r.status);var d=await r.json(),posts=(d.data&&d.data.children)||[],n=0;posts.forEach(function(pst){var x=pst.data||{},url='https://www.reddit.com'+x.permalink;if(state.sources.some(function(s){return s.redditId===x.id||s.url===url}))return;var pt=tagsFrom(x.title);state.sources.push({id:id(),redditId:x.id,url:url,title:x.title||url,author:x.author||'',category:pt.category,tags:pt.tags.concat(x.link_flair_text?[x.link_flair_text]:[]),createdUtc:x.created_utc||0,score:x.score||0,createdAt:Date.now()});n++});after=(d.data&&d.data.after)||'';$('redditNextBtn').disabled=!after;$('redditSyncStatus').textContent='Indexed '+n+' new posts from '+posts.length+' results.';save()}catch(e){$('redditSyncStatus').textContent='Sync failed: '+e.message+'. Reddit may also block direct browser requests; a server-side proxy may be needed.'}}
function voiceList(){return window.speechSynthesis?speechSynthesis.getVoices():[]}
function fillVoices(){var v=voiceList(),sel=$('voiceSelect');sel.innerHTML=v.map(function(x,i){return '<option value="'+i+'">'+esc(x.name)+' — '+esc(x.lang)+'</option>'}).join('');var fi=v.findIndex(function(x){return x.voiceURI===state.prefs.favoriteVoiceURI});if(fi>=0)sel.value=String(fi);renderVoices()}
function renderVoices(){var q=($('voiceSearch').value||'').toLowerCase();$('voiceList').innerHTML=voiceList().filter(function(v){return !q||(v.name+' '+v.lang).toLowerCase().indexOf(q)>=0}).map(function(v){return '<div class="voice-row"><div><div class="voice-name">'+esc(v.name)+'</div><div class="voice-lang">'+esc(v.lang)+'</div></div><button class="ghost compact" data-voice-uri="'+esc(v.voiceURI)+'">'+(v.voiceURI===state.prefs.favoriteVoiceURI?'★':'☆')+'</button></div>'}).join('')}
function splitText(t){var out=[],s=String(t||'').match(/[\s\S]{1,850}(?:\s|$)/g)||[t];s.forEach(function(x){if(x.trim())out.push(x.trim())});return out}
function play(i){var s=state.scripts.find(function(x){return x.id===i});if(!s)return;stop();current=s;chunks=splitText(s.text);chunk=0;$('playerTitle').textContent=s.title;$('playerMeta').textContent=[s.author,s.category,wc(s.text)+' words'].filter(Boolean).join(' · ');$('playerText').textContent=s.text;fillVoices();openD('playerDialog');speak()}
function speak(){if(!current||!chunks.length)return;speechSynthesis.cancel();paused=false;var u=new SpeechSynthesisUtterance(chunks[chunk]),v=voiceList(),ix=Number($('voiceSelect').value);if(v[ix])u.voice=v[ix];u.rate=Number($('rateRange').value);u.pitch=Number($('pitchRange').value);u.volume=Number($('volumeRange').value);u.onend=function(){chunk++;if(chunk<chunks.length)speak();else{chunk=0;$('playPauseBtn').textContent='▶';progress(1)}};speechSynthesis.speak(u);$('playPauseBtn').textContent='Ⅱ';progress(chunk/chunks.length)}
function progress(x){$('progressBar').style.width=Math.round(x*100)+'%';$('progressText').textContent=Math.min(chunk+1,chunks.length)+' of '+(chunks.length||1)+' sections'}
function stop(){if(window.speechSynthesis)speechSynthesis.cancel();paused=false;$('playPauseBtn').textContent='▶'}
function exportData(){var b=new Blob([JSON.stringify({version:3,exportedAt:new Date().toISOString(),scripts:state.scripts,sources:state.sources,prefs:state.prefs},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='WhisperVault-backup.json';a.click()}
async function importData(f){try{var x=JSON.parse(await f.text());state={scripts:x.scripts||[],sources:x.sources||[],prefs:Object.assign({},empty.prefs,x.prefs||{})};save();alert('Backup imported.')}catch(e){alert('Import failed: '+e.message)}}
document.addEventListener('click',function(e){var b=e.target.closest('button,[data-play],[data-edit],[data-fav],[data-delete],[data-use-source],[data-source-delete],[data-voice-uri]');if(!b)return;if(b.dataset.closeDialog)return closeD(b.dataset.closeDialog);if(b.dataset.play)return play(b.dataset.play);if(b.dataset.edit)return edit(b.dataset.edit);if(b.dataset.fav){var s=state.scripts.find(function(x){return x.id===b.dataset.fav});if(s){s.favorite=!s.favorite;save()}return}if(b.dataset.delete){if(confirm('Delete this script from this device?')){state.scripts=state.scripts.filter(function(x){return x.id!==b.dataset.delete});save()}return}if(b.dataset.useSource){resetForm(state.sources.find(function(x){return x.id===b.dataset.useSource}));openD('scriptDialog');return}if(b.dataset.sourceDelete){state.sources=state.sources.filter(function(x){return x.id!==b.dataset.sourceDelete});save();return}if(b.dataset.voiceUri){state.prefs.favoriteVoiceURI=b.dataset.voiceUri;save();fillVoices()}});
$('scriptForm').addEventListener('submit',function(e){e.preventDefault();var now=Date.now(),old=editId?state.scripts.find(function(x){return x.id===editId}):null,item={id:editId||id(),title:$('scriptTitle').value.trim(),author:$('scriptAuthor').value.trim(),category:$('scriptCategory').value,tags:$('scriptTags').value.split(',').map(function(x){return x.trim()}).filter(Boolean),source:$('scriptSource').value.trim(),permission:$('scriptPermission').value,text:$('scriptText').value.trim(),favorite:old?!!old.favorite:false,createdAt:old?old.createdAt:now,updatedAt:now};if(!item.title||!item.text)return;if(old)state.scripts=state.scripts.map(function(x){return x.id===editId?item:x});else state.scripts.push(item);save();closeD('scriptDialog')});
$('addScriptBtn').onclick=$('emptyAddBtn').onclick=$('navAdd').onclick=function(){resetForm();openD('scriptDialog')};$('addSourcesBtn').onclick=$('addSourcesBtn2').onclick=function(){openD('sourcesDialog')};$('saveSourcesBtn').onclick=addLinks;
$('redditSyncBtn').onclick=$('redditSyncBtn2').onclick=function(){$('redditToken').value=sessionStorage.getItem('wv_reddit_token')||'';openD('redditSyncDialog')};$('redditFetchBtn').onclick=function(){reddit(false)};$('redditNextBtn').onclick=function(){reddit(true)};$('openRedditSearchBtn').onclick=function(){window.open('https://www.reddit.com/r/gonewildaudio/search/?q=%5BScript%20Offer%5D&restrict_sr=1&sort=new','_blank','noopener')};
$('parseTitleBtn').onclick=function(){var p=tagsFrom($('scriptTitle').value);if(p.category)$('scriptCategory').value=p.category;$('scriptTags').value=[...new Set($('scriptTags').value.split(',').map(function(x){return x.trim()}).filter(Boolean).concat(p.tags))].join(', ')};$('pasteClipboardBtn').onclick=async function(){try{$('scriptText').value=await navigator.clipboard.readText()}catch(e){alert('Clipboard access was blocked. Tap and hold in the script box and choose Paste.')}};
$('exportBtn').onclick=exportData;$('importBackupBtn').onclick=function(){$('backupFileInput').click()};$('backupFileInput').onchange=function(e){if(e.target.files[0])importData(e.target.files[0]);e.target.value=''};$('settingsBtn').onclick=function(){openD('settingsDialog')};$('navVoices').onclick=function(){fillVoices();openD('voicesDialog')};$('navSources').onclick=function(){document.querySelector('.source-section').scrollIntoView({behavior:'smooth'})};
$('clearAllBtn').onclick=function(){if(confirm('Delete all WhisperVault local data on this device?')){state=clone(empty);localStorage.removeItem(KEY);save()}};$('searchInput').oninput=render;$('categoryFilter').onchange=render;$('sortSelect').onchange=render;$('voiceSearch').oninput=renderVoices;
$('rateRange').oninput=function(e){$('rateValue').textContent=Number(e.target.value).toFixed(2)+'×';state.prefs.rate=Number(e.target.value)};$('pitchRange').oninput=function(e){$('pitchValue').textContent=Number(e.target.value).toFixed(2);state.prefs.pitch=Number(e.target.value)};$('volumeRange').oninput=function(e){$('volumeValue').textContent=Math.round(Number(e.target.value)*100)+'%';state.prefs.volume=Number(e.target.value)};
$('playPauseBtn').onclick=function(){if(!speechSynthesis.speaking)return speak();if(paused){speechSynthesis.resume();paused=false;$('playPauseBtn').textContent='Ⅱ'}else{speechSynthesis.pause();paused=true;$('playPauseBtn').textContent='▶'}};$('stopBtn').onclick=function(){stop();chunk=0;progress(0)};$('rewindBtn').onclick=function(){chunk=Math.max(0,chunk-1);speak()};$('favoriteVoiceBtn').onclick=function(){var v=voiceList()[Number($('voiceSelect').value)];if(v){state.prefs.favoriteVoiceURI=v.voiceURI;save();fillVoices()}};
if(!localStorage.getItem(AGE))$('ageGate').hidden=false;$('enterBtn').onclick=function(){localStorage.setItem(AGE,'1');$('ageGate').hidden=true};$('leaveBtn').onclick=function(){location.href='about:blank'};
if(window.speechSynthesis){speechSynthesis.onvoiceschanged=fillVoices;setTimeout(fillVoices,200)}$('rateRange').value=state.prefs.rate;$('pitchRange').value=state.prefs.pitch;$('volumeRange').value=state.prefs.volume;if('serviceWorker' in navigator&&location.protocol.indexOf('http')===0)navigator.serviceWorker.register('./sw.js').catch(function(){});render();
})();
